ARG sourceimage=freqtradeorg/freqtrade
ARG sourcetag=stable

FROM ${sourceimage}:${sourcetag}

USER root
RUN pip install --upgrade pip

USER ftuser
RUN --mount=type=cache,target=/home/ftuser/.cache/pip \
    pip install --user --no-cache-dir tensorflow h5py

ENV PATH=/home/ftuser/.local/bin:$PATH
